// Department assistants
#define JOB_ASSISTANT_SRV "Servicer"
#define JOB_ASSISTANT_ENG "Tech Support"
#define JOB_ASSISTANT_MED "Medical Assistant"
#define JOB_ASSISTANT_SCI "Lab Assistant"
#define JOB_ASSISTANT_SEC "Brig Clerk"
#define JOB_DISPLAY_ORDER_ASSISTANT_SRV 36
#define JOB_DISPLAY_ORDER_ASSISTANT_ENG 37
#define JOB_DISPLAY_ORDER_ASSISTANT_MED 38
#define JOB_DISPLAY_ORDER_ASSISTANT_SCI 39
#define JOB_DISPLAY_ORDER_ASSISTANT_SEC 40
